version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: build.bat
artifacts:
- path: artifacts
  name: artifacts
- path: artifacts\*.nupkg
  name: NuGet Packages
